package com.sdkit.paylib.paylibpayment.impl.domain.network.response.invoice;

import java.util.List;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.StringSerializer;

/* loaded from: classes5.dex */
public final class InvoicePaymentInfoJson$$a implements GeneratedSerializer {

    /* renamed from: a */
    public static final InvoicePaymentInfoJson$$a f5431a;

    /* renamed from: b */
    public static final /* synthetic */ PluginGeneratedSerialDescriptor f5432b;

    static {
        InvoicePaymentInfoJson$$a invoicePaymentInfoJson$$a = new InvoicePaymentInfoJson$$a();
        f5431a = invoicePaymentInfoJson$$a;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.sdkit.paylib.paylibpayment.impl.domain.network.response.invoice.InvoicePaymentInfoJson", invoicePaymentInfoJson$$a, 22);
        pluginGeneratedSerialDescriptor.addElement("payment_date", true);
        pluginGeneratedSerialDescriptor.addElement("payment_id", true);
        pluginGeneratedSerialDescriptor.addElement("partner_client_id", true);
        pluginGeneratedSerialDescriptor.addElement("card_id", true);
        pluginGeneratedSerialDescriptor.addElement("name", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("masked_pan", true);
        pluginGeneratedSerialDescriptor.addElement("expiry_date", true);
        pluginGeneratedSerialDescriptor.addElement("cardholder", true);
        pluginGeneratedSerialDescriptor.addElement("image", true);
        pluginGeneratedSerialDescriptor.addElement("payment_system", true);
        pluginGeneratedSerialDescriptor.addElement("payment_system_image", true);
        pluginGeneratedSerialDescriptor.addElement("paysys", true);
        pluginGeneratedSerialDescriptor.addElement("paysys_code", true);
        pluginGeneratedSerialDescriptor.addElement("paysys_image", true);
        pluginGeneratedSerialDescriptor.addElement("payment_params", true);
        pluginGeneratedSerialDescriptor.addElement("payment_way", true);
        pluginGeneratedSerialDescriptor.addElement("payment_way_code", true);
        pluginGeneratedSerialDescriptor.addElement("payment_way_logo", true);
        pluginGeneratedSerialDescriptor.addElement("bank_info", true);
        pluginGeneratedSerialDescriptor.addElement("device_info", true);
        pluginGeneratedSerialDescriptor.addElement("loyalty_info", true);
        f5432b = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    /* renamed from: a, reason: merged with bridge method [inline-methods] */
    public InvoicePaymentInfoJson deserialize(Decoder decoder) {
        Object objDecodeNullableSerializableElement;
        Object objDecodeNullableSerializableElement2;
        Object objDecodeNullableSerializableElement3;
        Object objDecodeNullableSerializableElement4;
        Object objDecodeNullableSerializableElement5;
        Object obj;
        Object obj2;
        Object obj3;
        Object obj4;
        Object obj5;
        Object obj6;
        Object obj7;
        Object objDecodeNullableSerializableElement6;
        Object objDecodeNullableSerializableElement7;
        Object objDecodeNullableSerializableElement8;
        Object objDecodeNullableSerializableElement9;
        Object objDecodeNullableSerializableElement10;
        Object objDecodeNullableSerializableElement11;
        Object objDecodeNullableSerializableElement12;
        Object objDecodeNullableSerializableElement13;
        Object objDecodeNullableSerializableElement14;
        Object objDecodeNullableSerializableElement15;
        int i;
        KSerializer[] kSerializerArr;
        Object objDecodeNullableSerializableElement16;
        Object objDecodeNullableSerializableElement17;
        Object objDecodeNullableSerializableElement18;
        Object objDecodeNullableSerializableElement19;
        Object objDecodeNullableSerializableElement20;
        Object objDecodeNullableSerializableElement21;
        Object objDecodeNullableSerializableElement22;
        Object objDecodeNullableSerializableElement23;
        Object objDecodeNullableSerializableElement24;
        Object objDecodeNullableSerializableElement25;
        Object obj8;
        int i2;
        Object obj9;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor = getDescriptor();
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(descriptor);
        KSerializer[] kSerializerArr2 = InvoicePaymentInfoJson.f5408w;
        Object objDecodeNullableSerializableElement26 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            Object objDecodeNullableSerializableElement27 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 0, stringSerializer, null);
            objDecodeNullableSerializableElement11 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 1, stringSerializer, null);
            objDecodeNullableSerializableElement12 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 2, stringSerializer, null);
            objDecodeNullableSerializableElement13 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 3, stringSerializer, null);
            objDecodeNullableSerializableElement14 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 4, stringSerializer, null);
            Object objDecodeNullableSerializableElement28 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 5, stringSerializer, null);
            Object objDecodeNullableSerializableElement29 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 6, stringSerializer, null);
            Object objDecodeNullableSerializableElement30 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 7, stringSerializer, null);
            Object objDecodeNullableSerializableElement31 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 8, stringSerializer, null);
            Object objDecodeNullableSerializableElement32 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 9, stringSerializer, null);
            objDecodeNullableSerializableElement15 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 10, stringSerializer, null);
            Object objDecodeNullableSerializableElement33 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 11, stringSerializer, null);
            Object objDecodeNullableSerializableElement34 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 12, stringSerializer, null);
            Object objDecodeNullableSerializableElement35 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 13, stringSerializer, null);
            Object objDecodeNullableSerializableElement36 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 14, stringSerializer, null);
            Object objDecodeNullableSerializableElement37 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 15, kSerializerArr2[15], null);
            objDecodeNullableSerializableElement7 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 16, stringSerializer, null);
            obj7 = objDecodeNullableSerializableElement37;
            objDecodeNullableSerializableElement6 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 17, stringSerializer, null);
            objDecodeNullableSerializableElement8 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 18, stringSerializer, null);
            objDecodeNullableSerializableElement9 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 19, InvoiceBankInfoJson$$a.f5281a, null);
            Object objDecodeNullableSerializableElement38 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 20, InvoiceDeviceInfoJson$$a.f5334a, null);
            objDecodeNullableSerializableElement10 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 21, InvoiceAppliedLoyaltyJson$$a.f5275a, null);
            obj2 = objDecodeNullableSerializableElement31;
            obj = objDecodeNullableSerializableElement32;
            obj3 = objDecodeNullableSerializableElement30;
            obj4 = objDecodeNullableSerializableElement29;
            objDecodeNullableSerializableElement5 = objDecodeNullableSerializableElement36;
            objDecodeNullableSerializableElement4 = objDecodeNullableSerializableElement35;
            objDecodeNullableSerializableElement = objDecodeNullableSerializableElement34;
            objDecodeNullableSerializableElement3 = objDecodeNullableSerializableElement33;
            obj5 = objDecodeNullableSerializableElement28;
            i = 4194303;
            obj6 = objDecodeNullableSerializableElement27;
            objDecodeNullableSerializableElement2 = objDecodeNullableSerializableElement38;
        } else {
            boolean z = true;
            int i4 = 0;
            Object obj10 = null;
            Object objDecodeNullableSerializableElement39 = null;
            Object objDecodeNullableSerializableElement40 = null;
            Object objDecodeNullableSerializableElement41 = null;
            objDecodeNullableSerializableElement = null;
            Object objDecodeNullableSerializableElement42 = null;
            Object objDecodeNullableSerializableElement43 = null;
            objDecodeNullableSerializableElement2 = null;
            objDecodeNullableSerializableElement3 = null;
            objDecodeNullableSerializableElement4 = null;
            objDecodeNullableSerializableElement5 = null;
            Object obj11 = null;
            Object obj12 = null;
            Object obj13 = null;
            Object obj14 = null;
            Object obj15 = null;
            Object obj16 = null;
            Object obj17 = null;
            Object obj18 = null;
            Object obj19 = null;
            Object objDecodeNullableSerializableElement44 = null;
            while (z) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(descriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        z = false;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 0:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement44 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 0, StringSerializer.INSTANCE, objDecodeNullableSerializableElement44);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 1;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 1:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 1, StringSerializer.INSTANCE, obj19);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 2;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 2:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 2, StringSerializer.INSTANCE, obj18);
                        obj8 = objDecodeNullableSerializableElement39;
                        objDecodeNullableSerializableElement25 = obj19;
                        i2 = 4;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 3:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 3, StringSerializer.INSTANCE, obj17);
                        obj8 = objDecodeNullableSerializableElement39;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i2 = 8;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 4:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 4, StringSerializer.INSTANCE, obj16);
                        obj8 = objDecodeNullableSerializableElement39;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i2 = 16;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 5:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 5, StringSerializer.INSTANCE, obj15);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 32;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 6:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 6, StringSerializer.INSTANCE, obj14);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 64;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 7:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 7, StringSerializer.INSTANCE, obj13);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 128;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 8:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 8, StringSerializer.INSTANCE, obj12);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 256;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 9:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement17 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 9, StringSerializer.INSTANCE, obj11);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 512;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 10:
                        kSerializerArr = kSerializerArr2;
                        objDecodeNullableSerializableElement16 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 10, StringSerializer.INSTANCE, obj10);
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 1024;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 11:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 2048;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement3 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 11, StringSerializer.INSTANCE, objDecodeNullableSerializableElement3);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 12:
                        obj9 = obj10;
                        objDecodeNullableSerializableElement = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 12, StringSerializer.INSTANCE, objDecodeNullableSerializableElement);
                        i3 = 4096;
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = i3;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj9;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 13:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 8192;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement4 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 13, StringSerializer.INSTANCE, objDecodeNullableSerializableElement4);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 14:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 16384;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement5 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 14, StringSerializer.INSTANCE, objDecodeNullableSerializableElement5);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 15:
                        obj9 = obj10;
                        objDecodeNullableSerializableElement39 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 15, kSerializerArr2[15], objDecodeNullableSerializableElement39);
                        i3 = 32768;
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = i3;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj9;
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 16:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 65536;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement41 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 16, StringSerializer.INSTANCE, objDecodeNullableSerializableElement41);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 17:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 131072;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement40 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 17, StringSerializer.INSTANCE, objDecodeNullableSerializableElement40);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 18:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 262144;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement42 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 18, StringSerializer.INSTANCE, objDecodeNullableSerializableElement42);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 19:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 524288;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement43 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 19, InvoiceBankInfoJson$$a.f5281a, objDecodeNullableSerializableElement43);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 20:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 1048576;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement2 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 20, InvoiceDeviceInfoJson$$a.f5334a, objDecodeNullableSerializableElement2);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    case 21:
                        kSerializerArr = kSerializerArr2;
                        obj8 = objDecodeNullableSerializableElement39;
                        i2 = 2097152;
                        objDecodeNullableSerializableElement17 = obj11;
                        objDecodeNullableSerializableElement18 = obj12;
                        objDecodeNullableSerializableElement19 = obj13;
                        objDecodeNullableSerializableElement20 = obj14;
                        objDecodeNullableSerializableElement21 = obj15;
                        objDecodeNullableSerializableElement22 = obj16;
                        objDecodeNullableSerializableElement23 = obj17;
                        objDecodeNullableSerializableElement24 = obj18;
                        objDecodeNullableSerializableElement25 = obj19;
                        objDecodeNullableSerializableElement16 = obj10;
                        objDecodeNullableSerializableElement26 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 21, InvoiceAppliedLoyaltyJson$$a.f5275a, objDecodeNullableSerializableElement26);
                        i4 |= i2;
                        objDecodeNullableSerializableElement39 = obj8;
                        obj19 = objDecodeNullableSerializableElement25;
                        obj18 = objDecodeNullableSerializableElement24;
                        obj17 = objDecodeNullableSerializableElement23;
                        obj16 = objDecodeNullableSerializableElement22;
                        obj15 = objDecodeNullableSerializableElement21;
                        obj14 = objDecodeNullableSerializableElement20;
                        obj13 = objDecodeNullableSerializableElement19;
                        obj12 = objDecodeNullableSerializableElement18;
                        obj11 = objDecodeNullableSerializableElement17;
                        obj10 = objDecodeNullableSerializableElement16;
                        kSerializerArr2 = kSerializerArr;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            Object obj20 = obj10;
            obj = obj11;
            obj2 = obj12;
            obj3 = obj13;
            obj4 = obj14;
            obj5 = obj15;
            obj6 = objDecodeNullableSerializableElement44;
            obj7 = objDecodeNullableSerializableElement39;
            objDecodeNullableSerializableElement6 = objDecodeNullableSerializableElement40;
            objDecodeNullableSerializableElement7 = objDecodeNullableSerializableElement41;
            objDecodeNullableSerializableElement8 = objDecodeNullableSerializableElement42;
            objDecodeNullableSerializableElement9 = objDecodeNullableSerializableElement43;
            objDecodeNullableSerializableElement10 = objDecodeNullableSerializableElement26;
            objDecodeNullableSerializableElement11 = obj19;
            objDecodeNullableSerializableElement12 = obj18;
            objDecodeNullableSerializableElement13 = obj17;
            objDecodeNullableSerializableElement14 = obj16;
            objDecodeNullableSerializableElement15 = obj20;
            i = i4;
        }
        compositeDecoderBeginStructure.endStructure(descriptor);
        return new InvoicePaymentInfoJson(i, (String) obj6, (String) objDecodeNullableSerializableElement11, (String) objDecodeNullableSerializableElement12, (String) objDecodeNullableSerializableElement13, (String) objDecodeNullableSerializableElement14, (String) obj5, (String) obj4, (String) obj3, (String) obj2, (String) obj, (String) objDecodeNullableSerializableElement15, (String) objDecodeNullableSerializableElement3, (String) objDecodeNullableSerializableElement, (String) objDecodeNullableSerializableElement4, (String) objDecodeNullableSerializableElement5, (List) obj7, (String) objDecodeNullableSerializableElement7, (String) objDecodeNullableSerializableElement6, (String) objDecodeNullableSerializableElement8, (InvoiceBankInfoJson) objDecodeNullableSerializableElement9, (InvoiceDeviceInfoJson) objDecodeNullableSerializableElement2, (InvoiceAppliedLoyaltyJson) objDecodeNullableSerializableElement10, null);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] childSerializers() {
        KSerializer[] kSerializerArr = InvoicePaymentInfoJson.f5408w;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[15]), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(InvoiceBankInfoJson$$a.f5281a), BuiltinSerializersKt.getNullable(InvoiceDeviceInfoJson$$a.f5334a), BuiltinSerializersKt.getNullable(InvoiceAppliedLoyaltyJson$$a.f5275a)};
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public SerialDescriptor getDescriptor() {
        return f5432b;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }

    @Override // kotlinx.serialization.SerializationStrategy
    /* renamed from: a, reason: merged with bridge method [inline-methods] */
    public void serialize(Encoder encoder, InvoicePaymentInfoJson value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor = getDescriptor();
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(descriptor);
        InvoicePaymentInfoJson.m4384a(value, compositeEncoderBeginStructure, descriptor);
        compositeEncoderBeginStructure.endStructure(descriptor);
    }
}
