package com.sdkit.paylib.paylibpayment.impl.domain.network.response.invoice;

import com.sdkit.paylib.paylibpayment.api.network.entity.invoice.InvoiceCardPaymentWay;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.StringSerializer;

/* loaded from: classes5.dex */
public final class InvoiceCardJson$$a implements GeneratedSerializer {

    /* renamed from: a */
    public static final InvoiceCardJson$$a f5301a;

    /* renamed from: b */
    public static final /* synthetic */ PluginGeneratedSerialDescriptor f5302b;

    static {
        InvoiceCardJson$$a invoiceCardJson$$a = new InvoiceCardJson$$a();
        f5301a = invoiceCardJson$$a;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.sdkit.paylib.paylibpayment.impl.domain.network.response.invoice.InvoiceCardJson", invoiceCardJson$$a, 18);
        pluginGeneratedSerialDescriptor.addElement("card_id", false);
        pluginGeneratedSerialDescriptor.addElement("name", true);
        pluginGeneratedSerialDescriptor.addElement("status", true);
        pluginGeneratedSerialDescriptor.addElement("masked_pan", true);
        pluginGeneratedSerialDescriptor.addElement("expiry_date", true);
        pluginGeneratedSerialDescriptor.addElement("cardholder", true);
        pluginGeneratedSerialDescriptor.addElement("payment_system", true);
        pluginGeneratedSerialDescriptor.addElement("payment_system_image", true);
        pluginGeneratedSerialDescriptor.addElement("image", true);
        pluginGeneratedSerialDescriptor.addElement("paysys", true);
        pluginGeneratedSerialDescriptor.addElement("paysys_code", true);
        pluginGeneratedSerialDescriptor.addElement("paysys_image", true);
        pluginGeneratedSerialDescriptor.addElement("payment_way_code", true);
        pluginGeneratedSerialDescriptor.addElement("payment_way", true);
        pluginGeneratedSerialDescriptor.addElement("payment_way_logo", true);
        pluginGeneratedSerialDescriptor.addElement("bank_info", true);
        pluginGeneratedSerialDescriptor.addElement("loyalty_perhaps", true);
        pluginGeneratedSerialDescriptor.addElement("loyalty", true);
        f5302b = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    /* renamed from: a, reason: merged with bridge method [inline-methods] */
    public InvoiceCardJson deserialize(Decoder decoder) {
        int i;
        Object objDecodeNullableSerializableElement;
        Object objDecodeNullableSerializableElement2;
        Object obj;
        Object obj2;
        Object objDecodeNullableSerializableElement3;
        Object obj3;
        Object objDecodeNullableSerializableElement4;
        Object objDecodeNullableSerializableElement5;
        Object objDecodeNullableSerializableElement6;
        Object objDecodeNullableSerializableElement7;
        Object objDecodeNullableSerializableElement8;
        Object objDecodeNullableSerializableElement9;
        int i2;
        Object obj4;
        Object objDecodeNullableSerializableElement10;
        Object objDecodeNullableSerializableElement11;
        Object objDecodeNullableSerializableElement12;
        Object objDecodeNullableSerializableElement13;
        Object obj5;
        Object obj6;
        Object objDecodeNullableSerializableElement14;
        Object objDecodeNullableSerializableElement15;
        Object objDecodeNullableSerializableElement16;
        Object objDecodeNullableSerializableElement17;
        Object objDecodeNullableSerializableElement18;
        Object objDecodeNullableSerializableElement19;
        Object objDecodeNullableSerializableElement20;
        int i3;
        int i4;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor = getDescriptor();
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(descriptor);
        int i5 = 11;
        int i6 = 10;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(descriptor, 0);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            Object objDecodeNullableSerializableElement21 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 1, stringSerializer, null);
            objDecodeNullableSerializableElement5 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 2, stringSerializer, null);
            Object objDecodeNullableSerializableElement22 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 3, stringSerializer, null);
            objDecodeNullableSerializableElement6 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 4, stringSerializer, null);
            objDecodeNullableSerializableElement7 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 5, stringSerializer, null);
            objDecodeNullableSerializableElement12 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 6, stringSerializer, null);
            objDecodeNullableSerializableElement10 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 7, stringSerializer, null);
            Object objDecodeNullableSerializableElement23 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 8, stringSerializer, null);
            objDecodeNullableSerializableElement8 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 9, stringSerializer, null);
            objDecodeNullableSerializableElement13 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 10, stringSerializer, null);
            objDecodeNullableSerializableElement11 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 11, stringSerializer, null);
            Object objDecodeNullableSerializableElement24 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 12, C8574b.f5526a, null);
            objDecodeNullableSerializableElement4 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 13, stringSerializer, null);
            obj3 = objDecodeNullableSerializableElement24;
            Object objDecodeNullableSerializableElement25 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 14, stringSerializer, null);
            objDecodeNullableSerializableElement3 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 15, InvoiceBankInfoJson$$a.f5281a, null);
            objDecodeNullableSerializableElement9 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 16, BooleanSerializer.INSTANCE, null);
            obj2 = objDecodeNullableSerializableElement21;
            obj4 = objDecodeNullableSerializableElement22;
            objDecodeNullableSerializableElement = objDecodeNullableSerializableElement25;
            objDecodeNullableSerializableElement2 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 17, InvoiceCardLoyaltyInfoJson$$a.f5314a, null);
            obj = objDecodeNullableSerializableElement23;
            i2 = iDecodeIntElement;
            i = 262143;
        } else {
            int i7 = 17;
            boolean z = true;
            i = 0;
            Object objDecodeNullableSerializableElement26 = null;
            Object objDecodeNullableSerializableElement27 = null;
            Object objDecodeNullableSerializableElement28 = null;
            Object obj7 = null;
            Object obj8 = null;
            Object objDecodeNullableSerializableElement29 = null;
            objDecodeNullableSerializableElement = null;
            Object objDecodeNullableSerializableElement30 = null;
            Object obj9 = null;
            Object obj10 = null;
            Object obj11 = null;
            Object obj12 = null;
            Object obj13 = null;
            Object obj14 = null;
            Object obj15 = null;
            Object objDecodeNullableSerializableElement31 = null;
            objDecodeNullableSerializableElement2 = null;
            int iDecodeIntElement2 = 0;
            while (z) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(descriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        z = false;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 0:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(descriptor, 0);
                        i3 = 1;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 1:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        objDecodeNullableSerializableElement31 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 1, StringSerializer.INSTANCE, objDecodeNullableSerializableElement31);
                        i3 = 2;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 2:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 2, StringSerializer.INSTANCE, obj15);
                        i3 = 4;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 3:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 3, StringSerializer.INSTANCE, obj14);
                        objDecodeNullableSerializableElement20 = obj15;
                        i3 = 8;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 4:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 4, StringSerializer.INSTANCE, obj13);
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i3 = 16;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 5:
                        obj5 = objDecodeNullableSerializableElement26;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        obj6 = objDecodeNullableSerializableElement27;
                        objDecodeNullableSerializableElement17 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 5, StringSerializer.INSTANCE, obj12);
                        i3 = 32;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 6:
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        obj5 = objDecodeNullableSerializableElement26;
                        objDecodeNullableSerializableElement16 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 6, StringSerializer.INSTANCE, obj11);
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 64;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 7:
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 7, StringSerializer.INSTANCE, obj10);
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 128;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 8:
                        objDecodeNullableSerializableElement14 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 8, StringSerializer.INSTANCE, obj9);
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 256;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 9:
                        objDecodeNullableSerializableElement27 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 9, StringSerializer.INSTANCE, objDecodeNullableSerializableElement27);
                        i4 = 512;
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = i4;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 10:
                        Object objDecodeNullableSerializableElement32 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, i6, StringSerializer.INSTANCE, obj7);
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 1024;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        obj7 = objDecodeNullableSerializableElement32;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 11:
                        Object objDecodeNullableSerializableElement33 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, i5, StringSerializer.INSTANCE, obj8);
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 2048;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        obj8 = objDecodeNullableSerializableElement33;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 12:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 4096;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        objDecodeNullableSerializableElement29 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 12, C8574b.f5526a, objDecodeNullableSerializableElement29);
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 13:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 8192;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        objDecodeNullableSerializableElement30 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 13, StringSerializer.INSTANCE, objDecodeNullableSerializableElement30);
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 14:
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = 16384;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        objDecodeNullableSerializableElement = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 14, StringSerializer.INSTANCE, objDecodeNullableSerializableElement);
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 15:
                        objDecodeNullableSerializableElement28 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 15, InvoiceBankInfoJson$$a.f5281a, objDecodeNullableSerializableElement28);
                        i4 = 32768;
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = i4;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 16:
                        objDecodeNullableSerializableElement26 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, 16, BooleanSerializer.INSTANCE, objDecodeNullableSerializableElement26);
                        i4 = 65536;
                        obj5 = objDecodeNullableSerializableElement26;
                        obj6 = objDecodeNullableSerializableElement27;
                        i3 = i4;
                        objDecodeNullableSerializableElement14 = obj9;
                        objDecodeNullableSerializableElement15 = obj10;
                        objDecodeNullableSerializableElement16 = obj11;
                        objDecodeNullableSerializableElement17 = obj12;
                        objDecodeNullableSerializableElement18 = obj13;
                        objDecodeNullableSerializableElement19 = obj14;
                        objDecodeNullableSerializableElement20 = obj15;
                        i |= i3;
                        obj9 = objDecodeNullableSerializableElement14;
                        obj10 = objDecodeNullableSerializableElement15;
                        obj11 = objDecodeNullableSerializableElement16;
                        obj15 = objDecodeNullableSerializableElement20;
                        obj14 = objDecodeNullableSerializableElement19;
                        obj13 = objDecodeNullableSerializableElement18;
                        obj12 = objDecodeNullableSerializableElement17;
                        objDecodeNullableSerializableElement27 = obj6;
                        objDecodeNullableSerializableElement26 = obj5;
                        i7 = 17;
                        i5 = 11;
                        i6 = 10;
                    case 17:
                        objDecodeNullableSerializableElement2 = compositeDecoderBeginStructure.decodeNullableSerializableElement(descriptor, i7, InvoiceCardLoyaltyInfoJson$$a.f5314a, objDecodeNullableSerializableElement2);
                        i |= 131072;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            Object obj16 = objDecodeNullableSerializableElement27;
            obj = obj9;
            obj2 = objDecodeNullableSerializableElement31;
            objDecodeNullableSerializableElement3 = objDecodeNullableSerializableElement28;
            obj3 = objDecodeNullableSerializableElement29;
            objDecodeNullableSerializableElement4 = objDecodeNullableSerializableElement30;
            objDecodeNullableSerializableElement5 = obj15;
            objDecodeNullableSerializableElement6 = obj13;
            objDecodeNullableSerializableElement7 = obj12;
            objDecodeNullableSerializableElement8 = obj16;
            objDecodeNullableSerializableElement9 = objDecodeNullableSerializableElement26;
            i2 = iDecodeIntElement2;
            obj4 = obj14;
            Object obj17 = obj7;
            objDecodeNullableSerializableElement10 = obj10;
            objDecodeNullableSerializableElement11 = obj8;
            objDecodeNullableSerializableElement12 = obj11;
            objDecodeNullableSerializableElement13 = obj17;
        }
        compositeDecoderBeginStructure.endStructure(descriptor);
        return new InvoiceCardJson(i, i2, (String) obj2, (String) objDecodeNullableSerializableElement5, (String) obj4, (String) objDecodeNullableSerializableElement6, (String) objDecodeNullableSerializableElement7, (String) objDecodeNullableSerializableElement12, (String) objDecodeNullableSerializableElement10, (String) obj, (String) objDecodeNullableSerializableElement8, (String) objDecodeNullableSerializableElement13, (String) objDecodeNullableSerializableElement11, (InvoiceCardPaymentWay) obj3, (String) objDecodeNullableSerializableElement4, (String) objDecodeNullableSerializableElement, (InvoiceBankInfoJson) objDecodeNullableSerializableElement3, (Boolean) objDecodeNullableSerializableElement9, (InvoiceCardLoyaltyInfoJson) objDecodeNullableSerializableElement2, null);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        return new KSerializer[]{IntSerializer.INSTANCE, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(C8574b.f5526a), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(InvoiceBankInfoJson$$a.f5281a), BuiltinSerializersKt.getNullable(BooleanSerializer.INSTANCE), BuiltinSerializersKt.getNullable(InvoiceCardLoyaltyInfoJson$$a.f5314a)};
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public SerialDescriptor getDescriptor() {
        return f5302b;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }

    @Override // kotlinx.serialization.SerializationStrategy
    /* renamed from: a, reason: merged with bridge method [inline-methods] */
    public void serialize(Encoder encoder, InvoiceCardJson value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor = getDescriptor();
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(descriptor);
        InvoiceCardJson.m4341a(value, compositeEncoderBeginStructure, descriptor);
        compositeEncoderBeginStructure.endStructure(descriptor);
    }
}
