package com.blackhub.bronline.game.gui.blackpass.utils;

import androidx.compose.runtime.internal.StabilityInferred;
import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;

/* compiled from: BlackPassUtils.kt */
@StabilityInferred(parameters = 1)
/* loaded from: classes.dex */
public final class BlackPassUtils {
    public static final int $stable = 0;
    public static final int AWARD_IS_GET_PRIZE = 0;
    public static final int AWARD_IS_GET_PRIZE_IN_TASKS_OR_MARATHON = 4;
    public static final int AWARD_IS_SHOW_PRIZE_IN_MARATHON = 1;
    public static final int AWARD_IS_SHOW_PRIZE_IN_PRESENTS_COMPLETED = 3;
    public static final int AWARD_IS_SHOW_PRIZE_IN_PRESENTS_PREVIEW = 2;
    public static final int BP_PROGRESS_BAR_FULL = 100;
    public static final int BP_PROGRESS_BAR_HALF = 50;
    public static final int BP_PROGRESS_BAR_WHEN_HAS_PLUS = 5;
    public static final int CAR_AWARD_ID_2402 = 2402;
    public static final int CAR_AWARD_ID_2403 = 2403;
    public static final int CAR_AWARD_ID_2404 = 2404;
    public static final int CAR_AWARD_ID_2405 = 2405;
    public static final int CAR_AWARD_ID_2406 = 2406;
    public static final int CAR_AWARD_ID_2407 = 2407;
    public static final int CAR_AWARD_ID_670 = 670;
    public static final int CAR_AWARD_ID_671 = 671;
    public static final int CAR_AWARD_ID_672 = 672;
    public static final int CAR_AWARD_ID_673 = 673;
    public static final int CAR_AWARD_ID_674 = 674;
    public static final int DAYS_LEFT_UNTIL_SEASON_FINISH_HINT = 14;
    public static final int DEFAULT_DELUXE_PRICE = 1699;
    public static final int DEFAULT_LEVEL_PRICE = 150;
    public static final int DEFAULT_PREMIUM_PRICE = 599;
    public static final int DIALOG_ACTION_APPLY_LEVEL_UP = 0;
    public static final int DIALOG_ACTION_EXCHANGE_TASK = 2;
    public static final int DIALOG_ACTION_PURCHASE_PREMIUM = 3;
    public static final int DIALOG_ACTION_PURCHASE_PREMIUM_DELUXE = 4;
    public static final int DIALOG_ACTION_TOP_UP_YOUR_ACCOUNT = 1;
    public static final int EXCHANGE_TASK_COST = 10;
    public static final int FIRST_POS_IN_RATING = 0;
    public static final float FIVE_FLOAT = 5.0f;
    public static final int ID_PREMIUM = 1;
    public static final int ID_PREMIUM_DELUXE = 0;
    public static final int ID_PRIZE_ACCESSORIES = 11;
    public static final int ID_PRIZE_BLACK_COIN = 3;
    public static final int ID_PRIZE_BP_EXP = 10;
    public static final int ID_PRIZE_CAR = 5;
    public static final int ID_PRIZE_DISCOUNT_ACCESSORIES = 20;
    public static final int ID_PRIZE_DISCOUNT_CAR = 20;
    public static final int ID_PRIZE_DISCOUNT_PRODUCT = 20;
    public static final int ID_PRIZE_DISCOUNT_SERVICE = 20;
    public static final int ID_PRIZE_DISCOUNT_SET = 20;
    public static final int ID_PRIZE_DISCOUNT_SKIN = 20;
    public static final int ID_PRIZE_DISCOUNT_VIP = 20;
    public static final int ID_PRIZE_DUST = 21;
    public static final int ID_PRIZE_EXP = 1;
    public static final int ID_PRIZE_MONEY = 2;
    public static final int ID_PRIZE_RULLET = 4;
    public static final int ID_PRIZE_SET = 6;
    public static final int ID_PRIZE_SKIN = 11;
    public static final int ID_PRIZE_TIME_CAR = 5;
    public static final int ID_PRIZE_TIME_SKIN = 11;
    public static final int ID_PRIZE_VINYL = 20;
    public static final int ID_PRIZE_VIP_DAYS = 9;
    public static final int ID_PRIZE_VIP_HOURS = 9;
    public static final int ID_PRIZE_X2 = 8;

    @NotNull
    public static final BlackPassUtils INSTANCE = new BlackPassUtils();
    public static final int IS_FAIL = 0;
    public static final int IS_PREMIUM_REWARD = 1;
    public static final int IS_STANDARD_REWARD = 0;
    public static final int IS_SUCCESSFULLY = 1;
    public static final int JSON_LAYOUT_BP_ACTIVATE = 2;
    public static final int JSON_LAYOUT_BP_MAIN = 4;
    public static final int JSON_LAYOUT_BP_TASKS = 3;
    public static final int JSON_SIZE_FOR_MARATHON = 15;
    public static final int JSON_SIZE_FOR_STANDART = 30;
    public static final int LAST_CHANCE_FIFTH_LEVEL = 5;
    public static final int LAST_CHANCE_FIRST_LEVEL = 1;
    public static final int LAYOUT_ACTIVATE = 4;
    public static final int LAYOUT_PASS = 0;
    public static final int LAYOUT_RATING = 3;
    public static final int LAYOUT_TASKS = 1;
    public static final int MAX_LEVEL_FOR_OFFER = 71;
    public static final int MAX_VALUE_OF_EXPERIENCE = 1500;
    public static final int SECOND_POS_IN_RATING = 1;
    public static final int SKINS_AWARD_ID = 134;
    public static final int STATUS_PREMIUM = 2;
    public static final int STATUS_PREMIUM_DELUXE = 1;
    public static final int STATUS_STANDART = 0;
    public static final int STEP_FOR_TASKS_JSON = 3;
    public static final int TASK_ID_FIRST_POS = 0;
    public static final int TASK_NUM_FIRST_POS = 2;
    public static final int TASK_SIZE_IF_WITHOUT_PREMIUM = 30;
    public static final int TASK_SIZE_IF_WITH_PREMIUM = 45;
    public static final int TASK_TRACKING_TRACK_VALUE = 1;
    public static final int TASK_TRACKING_UNTRACK_VALUE = 0;
    public static final int TASK_TRACKING_VALUE = 3;
    public static final int TASK_TYPE_BTN_PREMIUM_TRACK = 6;
    public static final int TASK_TYPE_FIRST_POS = 1;
    public static final int TENTH_PART_OF_LEVEL = 10;
    public static final int THIRD_POS_IN_RATING = 2;
    public static final int TYPE_REWARD_SUPER = 1;
    public static final int TYPE_REWARD_USUAL = 0;
    public static final int TY_BP_SEND_JSON_TO_SERVER = -1;
    public static final int TY_CHANGE_LAYOUT = 0;
    public static final int TY_CONFIRMATION = 1;
    public static final int TY_GET_PRIZE = 2;
    public static final int TY_INITIALISATION = 0;
    public static final int TY_INIT_INTERFACE = -1;
    public static final int TY_LEVEL_UP = 1;
    public static final int TY_SEND_OPEN_BP = -2;
    public static final int TY_UPDATE_EXP_AND_LEVEL = 3;
    public static final int VALUE_IF_INIT_TASKS = 2;
    public static final int VALUE_IF_WITHOUT_PREMIUM = 0;
    public static final int VALUE_IF_WITH_PREMIUM = 1;
    public static final int VALUE_OF_LEVEL_UP = 1;
    public static final int WEEKLY_TASK_TYPE = 3;
    public static final float ZERO_POINT_ONE_FLOAT = 0.01f;
}

